{{- if include "ruby-test-apps.useInlineSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ruby-test-apps.fullname" . }}
  labels:
    {{- include "ruby-test-apps.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | quote }}
  {{- if .Values.railsMasterKey }}
  RAILS_MASTER_KEY: {{ .Values.railsMasterKey | quote }}
  {{- end }}
{{- end }}
